name = "yayasan-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
JWT_SECRET = "yayasan-secret-key-2026-change-in-production"

[[d1_databases]]
binding = "DB"
database_name = "yayasan-db"
database_id = "7a8c5b7b-9ee9-4824-9ec3-686d65fcef7c"

[[r2_buckets]]
binding = "R2"
bucket_name = "yayasan-files"
